### ISSUE TITLE
Hotstar

### ISSUE THREAD

**Issue by scorpsannav** [denobisipsis/adownloader#146]
Hotstar Not working

**Comment by Ashnaag** [comment]
Even I am not able to download video from Hotstar. Instead of downloading the actual Video from Hotstar, a small video clip is getting downloaded having message "This Version of Hotstar is no longer supported. Please download the latest version from the App store." Below is the screenshot for your reference.

![image](https://user-images.githubusercontent.com/54377665/82182492-fef97600-9901-11ea-8f13-768658bf6c05.png)

I had raised similar issue earlier as well, at that time I was informed that the error is coming for VIP videos. however the videos I am trying to download now are non VIP videos. Below are few video links for your reference,
https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/trouble-follows-shakuni/1000249416
https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/shakuni-gets-abducted/1000249418
https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/suryabhan-is-petrified/1000249421

**Comment by denobisipsis** [comment]
Fixed, but the first stream is drm

**Comment by scorpsannav** [comment]
Thanks a lot..

**Comment by denobisipsis** [comment]
Try updating ffmpeg

**Comment by denobisipsis** [comment]
Also you need vpn

**Comment by Ashnaag** [comment]
I have updated ffmpeg but still the chunks are not merging..Also please can you elaborate on how to use the VPN for downloading via ADownloader

**Comment by denobisipsis** [comment]
Simply run vpn at system-level.

**Comment by Ashnaag** [comment]
tried via tunnelbear and protonvpn but still no luck in merging the chunks

**Comment by padma-lakshmi** [comment]
for me working fine.

**Comment by Ashnaag** [comment]
Tried again by rebooting the system and deleting all the previously downloaded files but still facing the issue. Below is the log from the adownloder screen.

**1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4 downloaded
No such file**
Module caudiovideo up to date
Dont want to mux caps
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 318 chunks to download...
Getting manifest...
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/media-7/index.m3u8
www.hotstar.com
Name is hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Fixed mux-options:  false 
Module ffmpeg up to date
Downloading hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Processing m3u8 bitrate m3u8_190001920x1080
Captions deactivated
1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded
No such file
Module caudiovideo up to date
0.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded 
mkv on
Merging subtitles->...Wait the notification
Incrusting subtitles
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 318 chunks to download...
Getting manifest...
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/media-7/index.m3u8
www.hotstar.com
Name is hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Fixed mux-options:  false 
Module ffmpeg up to date
Downloading hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Processing m3u8 bitrate m3u8_190001920x1080
**1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded
No such file**
Module caudiovideo up to date
0.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mkv downloaded 
mkv on
Merging subtitles->...Wait the notification
Incrusting subtitles
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 318 chunks to download...
Getting manifest...
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/media-7/index.m3u8
www.hotstar.com
Name is hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Fixed mux-options:  false 
Module ffmpeg up to date
Downloading hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Processing m3u8 bitrate m3u8_190001920x1080
Found...6 links 
Subtitle's download & conversion OK
Getting and formatting captions...
hdntl=exp=1589896025~acl=%2f*~data=hdntl~hmac=8a367180c7008211a3f522b1f4f2cca8960e9936f2e6c17c2945293e01eb8164;
Getting manifest m3u8...
Module m3 up to date
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/master-phone.m3u8?hdnea=st=1589809520~exp=1589810120~acl=/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/*~data=ip=02019fbb882a203d154ab84d12690442030ead587cf214ae6f2ee24a75af-userid=798bbf12c8211977f6c40e30f9352ab014c4b5b87a1f0d18a38b333802b319e1~hmac=6411927c08827f51d3aa6cab3c2ea9b1a41027b045af592e594e8b292c598e89
https://hses4.akamaized.net/videos/hotstarint/forceup/1260025161/1586341016779/fcc2ab35a8cfbd1315af85b0085f1689/master-tv.m3u8
Module hotstar up to date
 good
Module redirector up to date
https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/trouble-follows-shakuni/1000249416
Searching streams...
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
Booting in 15 seconds
Running...
FFmpeg allowed_extensions activated. This is a newer FFmpeg so some operations may fail. Please post them
Ready...
 good
Thank you for contributing joshee_aasheesh
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	22-inichecks...set to Y
	15-getsubs...Y
	14-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	13-ydashwebm...false
	12-ydashmp4...false
	11-ychunk=...9000000
	10-muxoptions...false
	9-Audio output set to CONVERT AUDIO
	8-Video output set to CONVERT VIDEO
	7-Forcing proxy...N
	6-proxyuse...Use online proxies
	5-hdsparallel...set to 4
	4-hlsrelaunch...N
	3-m3delete...N
	2-m3parallel...set to 4
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

**Comment by denobisipsis** [comment]
Deactivate subtitles, thats  failing

**Comment by Ashnaag** [comment]
tried that. I have even re-installed adownloader but still merging of chunks is failing. All the Chunks are getting downloaded in their respective folders just merging of them is not happening with and without subtitles.

The issue is occurring for zee5 videos as well.

1.00B zeetvVaidehibecomesashapeshiftingserpentMainBhiArdhangini_hitypem3u8_233001920x1080.mp4 downloaded
No such file
Module caudiovideo up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Audio selected was muxed in final video. You have the original video in C:\Adownloader_New\downloads\zeetvVaidehibecomesashapeshiftingserpentMainBhiArdhangini_hitypem3u8_233001920x1080.mp4.original.mp4
Muxing m3u8 ufc audio files. If encrypted wait...
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 335 chunks to download...
Downloading audio too
zee5
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Getting manifest...
https://zee5vodnd.akamaized.net/hls1/1080p/tvshows/ONAIR_SHOWS/And_Tv/July2019/30072019/Seamless/Main_Bhi_Ardhangini_Ep133_Seamless_30072019_hi_cdd740f8.mp4/media-7/hdntl=exp=1589902233~acl=%2f*~data=hdntl~hmac=3e3c2c123be80985032e0e49a7de906ff31e173760bb430e75b4fb005b941649/stream.m3u8?aka_me_session_id=AAAAAAAAAACZ+8NeAAAAAH4k2OP3vdmO18zLJaB6Om+GDdFzuhQxkLdomMqm81KDiXtd1UT+orAJmmztgGndwCuWWFMRkHvN
www.zee5.com
Name is zeetvVaidehibecomesashapeshiftingserpentMainBhiArdhangini_hitypem3u8_233001920x1080.mp4
Fixed mux-options:  false 
audio is https://zee5vodnd.akamaized.net/hls1/1080p/tvshows/ONAIR_SHOWS/And_Tv/July2019/30072019/Seamless/Main_Bhi_Ardhangini_Ep133_Seamless_30072019_hi_cdd740f8.mp4/audio/aac/en/hdntl=exp=1589902233~acl=%2f*~data=hdntl~hmac=3e3c2c123be80985032e0e49a7de906ff31e173760bb430e75b4fb005b941649/stream.m3u8?aka_me_session_id=AAAAAAAAAACZ+8NeAAAAAH4k2OP3vdmO18zLJaB6Om+GDdFzuhQxkLdomMqm81KDiXtd1UT+orAJmmztgGndwCuWWFMRkHvN
Module ffmpeg up to date
Downloading zeetvVaidehibecomesashapeshiftingserpentMainBhiArdhangini_hitypem3u8_233001920x1080.mp4
Processing m3u8 bitrate m3u8_233001920x1080
Found...7 links 
Subs found in en
https://zee5vodnd.akamaized.net/hls1/1080p/tvshows/ONAIR_SHOWS/And_Tv/July2019/30072019/Seamless/Main_Bhi_Ardhangini_Ep133_Seamless_30072019_hi_cdd740f8.mp4/audio/aac/en/hdntl=exp=1589902233~acl=%2f*~data=hdntl~hmac=3e3c2c123be80985032e0e49a7de906ff31e173760bb430e75b4fb005b941649/stream.m3u8?aka_me_session_id=AAAAAAAAAACZ+8NeAAAAAH4k2OP3vdmO18zLJaB6Om+GDdFzuhQxkLdomMqm81KDiXtd1UT+orAJmmztgGndwCuWWFMRkHvN language hi 
Getting manifest m3u8...
hi
Module m3 up to date
https://zee5vodnd.akamaized.net/hls1/1080p/tvshows/ONAIR_SHOWS/And_Tv/July2019/30072019/Seamless/Main_Bhi_Ardhangini_Ep133_Seamless_30072019_hi_cdd740f8.mp4/index.m3u8?hdnea=st=1589814301~exp=1589817301~acl=/*~hmac=f7a8fdb6eb162f367b288ff4ad49cb2478163c0cd1eac32c75210bba536d50e8
Select language adding to URL ?lang=lang, i.e. ?lang=hi
There are these language possibilities: hi,
Not downloadable. DRM.
3 cycle
season 0-2-1155
0-1-248061
Found 1
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
Module zeetv up to date
 good
Module redirector up to date
https://www.zee5.com/tvshows/details/main-bhi-ardhangini/0-6-1248/vaidehi-becomes-a-shape-shifting-serpent-main-bhi-ardhangini/0-1-248061
Searching streams...
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
Booting in 15 seconds
Running...
FFmpeg allowed_extensions activated. This is a newer FFmpeg so some operations may fail. Please post them
Ready...
 good
Thank you for contributing joshee_aasheesh
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	22-inichecks...set to Y
	15-getsubs...N
	14-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	13-ydashwebm...false
	12-ydashmp4...false
	11-ychunk=...9000000
	10-muxoptions...false
	9-Audio output set to SAME
	8-Video output set to SAME
	7-Forcing proxy...N
	6-proxyuse...Use online proxies
	5-hdsparallel...set to 4
	4-hlsrelaunch...N
	3-m3delete...N
	2-m3parallel...set to 4
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader_New\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

I have added the screenshot of the options section as well for your reference. Please can you let me know if anything needs to be amended here for solving the issue.

![image](https://user-images.githubusercontent.com/54377665/82238585-2f1e3480-9955-11ea-8d60-15c109d4ee56.png)

Thanks.

**Comment by padma-lakshmi** [comment]
Just press on 16.ffmpeg (Press to update)

**Comment by Ashnaag** [comment]
Did that and got below response in the logs

Finished
Updating ffmpeg...

Post this the value for option 16 is same as that of the screen shot i.e. ffmpeg version git-2020-05-15-b18fd2b

**Comment by denobisipsis** [comment]
Please update option 1--> make a temp folder for the chunks.

**Comment by Ashnaag** [comment]
even after creating a temp folder for option 1, no luck :(

1.00B hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4 downloaded
No such file
Module caudiovideo up to date
Dont want to mux caps
Module isubs up to date
Chunks were preserved. If you want to delete them change m3delete in options.ini putting m3delete=1;
Muxing m3u8 files...

You have a new option called muxoptions

if you put false, the program uses ffmpeg with internal predefined options for muxing

if you put raw, the program doesnt use ffmpeg and makes a raw concatenating of chunks

if you put other, nothing, i.e. muxoptions=; , or valid ffmpeg options, program applies them

C:\Temp
Parallel downloading 4 chunks. To change it modify the field M3parallel
Using aria2c parallel
There are 318 chunks to download...
Getting manifest...
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/media-7/index.m3u8
www.hotstar.com
Name is hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Fixed mux-options:  false 
C:\Temp
Module ffmpeg up to date
Downloading hotstarTroubleFollowsShakunitypem3u8_190001920x1080.mp4
Processing m3u8 bitrate m3u8_190001920x1080
Captions deactivated
Found...6 links 
Subtitle's download & conversion OK
Getting and formatting captions...
hdntl=exp=1589959132~acl=%2f*~data=hdntl~hmac=8f9e926513bc5e1ae30bc781b463e3f07a713a7c84b9d93a3d4d6413671b7113;
Getting manifest m3u8...
Module m3 up to date
Selected proxy from IN but unused cause you're there
You are in IN
Module nproxy up to date
https://hses4.hotstar.com/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/master-phone.m3u8?hdnea=st=1589872621~exp=1589873221~acl=/videos/hotstarint/1260023688/1000249416/1589370750693/b6ccc7aa1189a6d541b5b5a962bdb968/*~data=ip=02019fbb8829203d1646bc4d1b6e577dccef61e7677170b9268ab4d814ad52-userid=798bbf12c8211977f6c40e30f9352ab014c4b5b87a1f0d18a38b333802b319e1~hmac=6121fb089a4640494f69e9bd0a48a8682f8f4adf78f6c01f42eaeda6780f41fb
https://hses4.akamaized.net/videos/hotstarint/forceup/1260025161/1586341016779/fcc2ab35a8cfbd1315af85b0085f1689/master-tv.m3u8
Module hotstar up to date
 good
Module redirector up to date
https://www.hotstar.com/in/tv/maharaj-ki-jai-ho/s-2570/trouble-follows-shakuni/1000249416
Searching streams...
Temp in options.ini updated to C:\Temp
You're up to date
Actual minor version d11f621fb32b847f45a02a96cdc429a5
Checking minor...wait...
You have the latest major version v19
Checking latest...
Booting in 27 seconds
Running...
FFmpeg allowed_extensions activated. This is a newer FFmpeg so some operations may fail. Please post them
Ready...
 good
Thank you for contributing joshee_aasheesh
Checking donation...
Donation...
Mux options false for internal use of ffmpeg. Dont change it if you dont know what are you doing
Structure...
	22-inichecks...set to Y
	15-getsubs...Y
	14-sout...#transcode{vcodec=mp4v,acodec=mpga,deinterlace,hq}:standard{access=file,mux=ts
	13-ydashwebm...false
	12-ydashmp4...false
	11-ychunk=...9000000
	10-muxoptions...false
	9-Audio output set to SAME
	8-Video output set to SAME
	7-Forcing proxy...N
	6-proxyuse...Use online proxies
	5-hdsparallel...set to 4
	4-hlsrelaunch...N
	3-m3delete...N
	2-m3parallel...set to 4
	1-fftemp not set
	0-Downloads folder set to C:\Adownloader_Latest\downloads
Options...
Adobe HDS funciona correctamente
AdobeHDS...
path...
SubtitleEdit...
modules...
rabcasm...
vlc...
ismdownloader...
ismdownloaderAVC1...
rtmpdump...
ffmpeg...
php...
SabreAMF...
external scripts...
curl...
7za...
aria2c...
curl...
Cacert...
Folders...
OK
Connection...
Inichecks...
Starting...
Adownloader Log...

**Comment by denobisipsis** [comment]
Just fixed, wait im updating

**Comment by denobisipsis** [comment]
Try now, activate subtitles, all is working, but make the search anew.

**Comment by padma-lakshmi** [comment]
Can you please fix the amazon primevideo.com also

**Comment by Ashnaag** [comment]
The issue is solved now. I have successfully downloaded videos from Zee5 and HotStar without any issue.

Thanks a ton for your help :)
